version: "3"

services:
  apiserver:
    image: puem2639/nodemon:v2
    volumes:
      - ./backend:/data
    ports:
      - 4000:4000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres-data:/var/lib/postgresql/d
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: example
      PGADMIN_DEFAULT_EMAIL: xxx@xxx.xxx